language: python
python: 3.5

env:
  global:
    - ETCD_VERSION=v3.0.13
  matrix:
    - TOXENV=py35
    - TOXENV=py34
    - TOXENV=py27
    - TOXENV=flake8

    - TOXENV=py35 ETCD_VERSION=v3.1.0-rc.0
    - TOXENV=py27 ETCD_VERSION=v3.1.0-rc.0

install:
    - pip install -U tox codecov
    - curl -L https://github.com/coreos/etcd/releases/download/$ETCD_VERSION/etcd-$ETCD_VERSION-linux-amd64.tar.gz -o etcd-$ETCD_VERSION-linux-amd64.tar.gz
    - tar xzvf etcd-$ETCD_VERSION-linux-amd64.tar.gz
    - export PATH=$PATH:etcd-$ETCD_VERSION-linux-amd64
    - etcd &

script: tox -e ${TOXENV}

after_success:
      - codecov

deploy:
  provider: pypi
  user: kragniz
  password:
    secure: YK7eGpk14nLqeH/c3y2UuQ5NHz+7L48Hj1zFX78o6BntF+xq7OhZpVOiLnStSW7CW70IXdSsuLhT6zPyzTemUWLZVAfF8uYdCCZkN8E0IVjTbEPkq4YK5HaQH4kSgWWN/B16vDQBpLCVVK6J2E+wI9Y9sKGWqBP0d2pJJd1T4wpBHZDzY8AFzo8UO+HP//iCX/yTeStqPz4tYT2dVtRFiyc1DKZWwZGxIInQS2QNAsT7eszuZDbBGrVXye+rm65nAxYY8SMxRbTlRqqUDyQ8nzdaHTHW8J5uDSWSd+OIeZQd/Sp51rH4JqaUTib0al+s0PhrOzOAxxygiSRkYaMNE9L5lNVIwaU8J5McCK9rVdXGFnP0UVgrlYetX0n4yksGpfqt2Ert+pH/kwrtQkREvSr/etOAqWwY87bqwRhhk5INxIGvRe/YP45BW6FFvInTc6ZBitIfUQ7Pv+2D/a7nfsvDEOi9eeGJCC7H5NYKreysIoP8jIhhNTjnsd3t/QfFqUTrlzAXBgW8zLlZASdjH3aUOgKZbRtSG3d32B/2ILgmUdSVi4jbMDYa5L8kZywusWfih2FHN86BaziMbZ+3o3vA134lzwXETo+H1lx62O0+QLAR2NPAEjQ7cEaR5WG4r48qPTFmehZWGSmfbX6j2MObkbTMF6FoXfqW/RcxOMk=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: kragniz/python-etcd3
    condition: $TOXENV == py27
